name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t vigneshdotnet/react-test .
      - run: docker run -e CI=true vigneshdotnet/react-test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: reacttrydocker
          environment_name: Reacttrydocker-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-894954005032
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
